In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("price.csv")
print(df.head())
print(df.describe())

   Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Location  Condition  \
0   1  1360         5          4       3       1970  Downtown  Excellent
1   2  4272         5          4       3       1958  Downtown  Excellent
2   3  3592         2          2       3       1938  Downtown       Good
3   4   966         4          2       2       1902  Suburban       Fair
4   5  4926         1          4       2       1975  Downtown       Fair

  Garage   Price
0     No  149919
1     No  424998
2     No  266746
3    Yes  244020
4    Yes  636056
                Id         Area     Bedrooms   Bathrooms       Floors  \
count  2000.000000  2000.000000  2000.000000  2000.00000  2000.000000
mean   1000.500000  2786.209500     3.003500     2.55250     1.993500
std     577.494589  1295.146799     1.424606     1.10899     0.809188
min       1.000000   501.000000     1.000000     1.00000     1.000000
25%     500.750000  1653.000000     2.000000     2.00000     1.000000
50%    1000.500000  2833.000000     3.000000     3.00000     2.000000
75%    1500.250000  3887.500000     4.000000     4.00000     3.000000
max    2000.000000  4999.000000     5.000000     4.00000     3.000000

         YearBuilt          Price
count  2000.000000    2000.000000
mean   1961.446000  537676.855000
std      35.926695  276428.845719
min    1900.000000   50005.000000
25%    1930.000000  300098.000000
50%    1961.000000  539254.000000
75%    1993.000000  780086.000000
max    2023.000000  999656.000000

In [3]:
print(df['Area'].duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
1995     True
1996     True
1997     True
1998    False
1999     True
Name: Area, Length: 2000, dtype: bool

In [4]:
df=df[~((df['Price']<100000) & (df['Area']>4000))]
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [5]:
df=df[~(df['Price']>952173) & (df['Area']<1000)]

In [6]:
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
8,9,630,2,2,1,1932,Rural,Poor,Yes,652878
17,18,974,2,2,1,1919,Downtown,Poor,Yes,905742
24,25,689,5,1,3,1900,Urban,Excellent,Yes,688668
39,40,741,4,1,3,1968,Downtown,Excellent,No,218393
...,...,...,...,...,...,...,...,...,...,...
1965,1966,741,2,4,3,1947,Downtown,Excellent,No,649262
1975,1976,578,5,3,1,1982,Suburban,Excellent,Yes,189570
1985,1986,907,5,1,2,1932,Urban,Poor,No,769148
1989,1990,647,5,3,3,1919,Rural,Excellent,No,60002
1993,1994,865,4,4,2,2020,Rural,Poor,No,308446

In [7]:
df1=df.drop(columns=["Id"])

In [8]:
relation=df1.corr(numeric_only=True)
print(relation)
df1['Location'].unique()

               Area  Bedrooms  Bathrooms    Floors  YearBuilt     Price
Area       1.000000  0.101832  -0.004161  0.031759   0.092509 -0.040052
Bedrooms   0.101832  1.000000  -0.013405  0.034655  -0.070148 -0.137222
Bathrooms -0.004161 -0.013405   1.000000 -0.031182  -0.001098  0.093741
Floors     0.031759  0.034655  -0.031182  1.000000   0.041803 -0.037442
YearBuilt  0.092509 -0.070148  -0.001098  0.041803   1.000000  0.012066
Price     -0.040052 -0.137222   0.093741 -0.037442   0.012066  1.000000

<StringArray>
['Suburban', 'Rural', 'Downtown', 'Urban']
Length: 4, dtype: str

In [9]:
dum=pd.get_dummies(df1['Location'],dtype=int,drop_first=True)
dum

      Rural  Suburban  Urban
3         0         1      0
8         1         0      0
17        0         0      0
24        0         0      1
39        0         0      0
...     ...       ...    ...
1965      0         0      0
1975      0         1      0
1985      0         0      1
1989      1         0      0
1993      1         0      0

[190 rows x 3 columns]

In [10]:
dum2=pd.get_dummies(df1['Condition'],dtype=int,drop_first=True)

In [11]:
dum2

      Fair  Good  Poor
3        1     0     0
8        0     0     1
17       0     0     1
24       0     0     0
39       0     0     0
...    ...   ...   ...
1965     0     0     0
1975     0     0     0
1985     0     0     1
1989     0     0     0
1993     0     0     1

[190 rows x 3 columns]

In [12]:
df1['Garage']=df1['Garage'].map({
    'Yes':1,
    'No':0
})
df1

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
3,966,4,2,2,1902,Suburban,Fair,1,244020
8,630,2,2,1,1932,Rural,Poor,1,652878
17,974,2,2,1,1919,Downtown,Poor,1,905742
24,689,5,1,3,1900,Urban,Excellent,1,688668
39,741,4,1,3,1968,Downtown,Excellent,0,218393
...,...,...,...,...,...,...,...,...,...
1965,741,2,4,3,1947,Downtown,Excellent,0,649262
1975,578,5,3,1,1982,Suburban,Excellent,1,189570
1985,907,5,1,2,1932,Urban,Poor,0,769148
1989,647,5,3,3,1919,Rural,Excellent,0,60002
1993,865,4,4,2,2020,Rural,Poor,0,308446

In [13]:
df1 = pd.concat([df1, dum, dum2], axis=1)
df1

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,Rural,Suburban,Urban,Fair,Good,Poor
3,966,4,2,2,1902,Suburban,Fair,1,244020,0,1,0,1,0,0
8,630,2,2,1,1932,Rural,Poor,1,652878,1,0,0,0,0,1
17,974,2,2,1,1919,Downtown,Poor,1,905742,0,0,0,0,0,1
24,689,5,1,3,1900,Urban,Excellent,1,688668,0,0,1,0,0,0
39,741,4,1,3,1968,Downtown,Excellent,0,218393,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,741,2,4,3,1947,Downtown,Excellent,0,649262,0,0,0,0,0,0
1975,578,5,3,1,1982,Suburban,Excellent,1,189570,0,1,0,0,0,0
1985,907,5,1,2,1932,Urban,Poor,0,769148,0,0,1,0,0,1
1989,647,5,3,3,1919,Rural,Excellent,0,60002,1,0,0,0,0,0
1993,865,4,4,2,2020,Rural,Poor,0,308446,1,0,0,0,0,1

In [14]:
df1.columns

Index(['Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt', 'Location',
       'Condition', 'Garage', 'Price', 'Rural', 'Suburban', 'Urban', 'Fair',
       'Good', 'Poor'],
      dtype='str')

In [15]:
df2=df1.drop(columns=['Location','Condition'])

In [16]:
df2

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Garage,Price,Rural,Suburban,Urban,Fair,Good,Poor
3,966,4,2,2,1902,1,244020,0,1,0,1,0,0
8,630,2,2,1,1932,1,652878,1,0,0,0,0,1
17,974,2,2,1,1919,1,905742,0,0,0,0,0,1
24,689,5,1,3,1900,1,688668,0,0,1,0,0,0
39,741,4,1,3,1968,0,218393,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,741,2,4,3,1947,0,649262,0,0,0,0,0,0
1975,578,5,3,1,1982,1,189570,0,1,0,0,0,0
1985,907,5,1,2,1932,0,769148,0,0,1,0,0,1
1989,647,5,3,3,1919,0,60002,1,0,0,0,0,0
1993,865,4,4,2,2020,0,308446,1,0,0,0,0,1

In [17]:

train=df2.sample(frac=0.8,random_state=0)
test=df2.drop(train.index)

In [18]:
relation=train.corr(numeric_only=True)

In [19]:
test
x_test=test.drop(columns=['Price'])
y_test=test['Price']
x_test['Intercept']=1
x_test

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Garage,Rural,Suburban,Urban,Fair,Good,Poor,Intercept
72,992,3,3,3,1979,1,1,0,0,0,1,0,1
248,516,2,1,1,1956,0,0,0,1,1,0,0,1
318,504,5,2,1,1925,0,0,0,0,1,0,0,1
412,912,4,4,2,1958,1,0,1,0,0,1,0,1
446,643,3,2,3,1923,0,0,1,0,1,0,0,1
477,999,4,1,1,2014,0,0,1,0,1,0,0,1
534,857,4,2,2,1932,1,0,0,0,0,0,0,1
572,904,2,1,2,1940,0,0,1,0,0,0,1,1
671,864,2,4,3,1956,1,1,0,0,0,1,0,1
752,760,5,1,3,1996,0,0,0,1,0,1,0,1
852,845,4,1,3,1928,0,0,1,0,0,0,0,1
892,701,2,1,2,1968,1,0,0,0,1,0,0,1
901,974,1,2,2,2000,1,0,0,1,1,0,0,1
959,827,5,2,1,1975,0,1,0,0,0,0,1,1
1012,941,4,3,2,1977,0,1,0,0,0,0,1,1
1022,540,2,4,1,1906,1,0,0,1,0,0,0,1
1025,841,1,2,3,1968,1,0,1,0,1,0,0,1
1063,653,5,2,2,1938,1,0,1,0,0,0,1,1
1068,560,3,2,2,2003,0,0,1,0,0,0,1,1
1139,992,5,2,2,1986,0,1,0,0,0,0,1,1
1171,875,1,3,2,1991,0,0,0,0,0,1,0,1
1312,784,5,3,3,2021,1,1,0,0,0,0,1,1
1328,538,2,4,2,1961,1,0,0,0,0,0,0,1
1430,816,3,4,1,1945,0,0,1,0,1,0,0,1
1528,629,5,1,3,2008,0,0,0,1,1,0,0,1
1546,769,4,1,2,1993,1,0,0,0,0,0,1,1
1615,802,5,1,1,1969,0,0,1,0,1,0,0,1
1633,988,1,4,1,1924,0,1,0,0,0,1,0,1
1685,520,3,2,1,1913,0,1,0,0,0,0,0,1
1716,535,5,1,2,1904,0,0,0,0,0,0,0,1
1742,982,3,4,1,1956,0,0,0,1,1,0,0,1
1819,736,2,3,2,1942,1,1,0,0,0,1,0,1
1825,785,3,1,2,1974,1,0,0,0,0,0,1,1
1850,743,3,3,3,1937,1,0,0,1,1,0,0,1
1871,594,3,1,2,1981,1,0,0,0,0,1,0,1
1937,741,4,4,3,1951,1,1,0,0,0,1,0,1
1942,964,5,2,1,2009,0,0,1,0,0,0,1,1
1961,924,4,3,3,1938,1,0,0,1,0,0,0,1

In [20]:
train.columns

Index(['Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt', 'Garage',
       'Price', 'Rural', 'Suburban', 'Urban', 'Fair', 'Good', 'Poor'],
      dtype='str')

In [21]:
x_train=train.drop(columns=['Price'])

In [22]:
y_train=train['Price']

In [23]:
x_train['Intercept']=1

In [24]:
x_train

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Garage,Rural,Suburban,Urban,Fair,Good,Poor,Intercept
1214,502,2,1,1,1909,1,0,0,1,0,0,1,1
919,841,1,1,2,1911,1,0,0,1,0,0,1,1
1756,940,5,2,3,1987,1,0,1,0,1,0,0,1
1105,900,1,1,2,1901,0,0,0,1,0,0,0,1
1414,501,1,1,1,1955,0,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1823,863,2,4,2,1955,1,1,0,0,1,0,0,1
1444,750,4,4,3,2003,1,1,0,0,0,0,1,1
511,633,3,1,1,2021,1,0,0,1,0,1,0,1
404,917,4,1,3,1950,0,0,1,0,0,0,0,1
1308,521,3,3,2,2008,1,0,0,1,0,1,0,1

In [25]:
import torch

In [26]:
x_test

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Garage,Rural,Suburban,Urban,Fair,Good,Poor,Intercept
72,992,3,3,3,1979,1,1,0,0,0,1,0,1
248,516,2,1,1,1956,0,0,0,1,1,0,0,1
318,504,5,2,1,1925,0,0,0,0,1,0,0,1
412,912,4,4,2,1958,1,0,1,0,0,1,0,1
446,643,3,2,3,1923,0,0,1,0,1,0,0,1
477,999,4,1,1,2014,0,0,1,0,1,0,0,1
534,857,4,2,2,1932,1,0,0,0,0,0,0,1
572,904,2,1,2,1940,0,0,1,0,0,0,1,1
671,864,2,4,3,1956,1,1,0,0,0,1,0,1
752,760,5,1,3,1996,0,0,0,1,0,1,0,1
852,845,4,1,3,1928,0,0,1,0,0,0,0,1
892,701,2,1,2,1968,1,0,0,0,1,0,0,1
901,974,1,2,2,2000,1,0,0,1,1,0,0,1
959,827,5,2,1,1975,0,1,0,0,0,0,1,1
1012,941,4,3,2,1977,0,1,0,0,0,0,1,1
1022,540,2,4,1,1906,1,0,0,1,0,0,0,1
1025,841,1,2,3,1968,1,0,1,0,1,0,0,1
1063,653,5,2,2,1938,1,0,1,0,0,0,1,1
1068,560,3,2,2,2003,0,0,1,0,0,0,1,1
1139,992,5,2,2,1986,0,1,0,0,0,0,1,1
1171,875,1,3,2,1991,0,0,0,0,0,1,0,1
1312,784,5,3,3,2021,1,1,0,0,0,0,1,1
1328,538,2,4,2,1961,1,0,0,0,0,0,0,1
1430,816,3,4,1,1945,0,0,1,0,1,0,0,1
1528,629,5,1,3,2008,0,0,0,1,1,0,0,1
1546,769,4,1,2,1993,1,0,0,0,0,0,1,1
1615,802,5,1,1,1969,0,0,1,0,1,0,0,1
1633,988,1,4,1,1924,0,1,0,0,0,1,0,1
1685,520,3,2,1,1913,0,1,0,0,0,0,0,1
1716,535,5,1,2,1904,0,0,0,0,0,0,0,1
1742,982,3,4,1,1956,0,0,0,1,1,0,0,1
1819,736,2,3,2,1942,1,1,0,0,0,1,0,1
1825,785,3,1,2,1974,1,0,0,0,0,0,1,1
1850,743,3,3,3,1937,1,0,0,1,1,0,0,1
1871,594,3,1,2,1981,1,0,0,0,0,1,0,1
1937,741,4,4,3,1951,1,1,0,0,0,1,0,1
1942,964,5,2,1,2009,0,0,1,0,0,0,1,1
1961,924,4,3,3,1938,1,0,0,1,0,0,0,1

In [27]:
X_numpy = x_train.to_numpy(dtype='float32')
y_numpy = y_train.to_numpy(dtype='float32')
x_tes=x_test.to_numpy(dtype='float32')
y_tes=y_test.to_numpy(dtype='float32')

In [28]:
x_torch=torch.from_numpy(X_numpy)
y_torch=torch.from_numpy(y_numpy).reshape(-1,1)
x_tes=torch.from_numpy(x_tes)
y_tes=torch.from_numpy(y_tes)

In [29]:
print(y_torch.size())
print(x_torch.size())
print(x_tes.size())

torch.Size([152, 1])
torch.Size([152, 13])
torch.Size([38, 13])

In [30]:
x_t=torch.t(x_torch)
print(x_t)
x_mul=torch.matmul(x_t,x_torch)
print(x_mul)

tensor([[502., 841., 940.,  ..., 633., 917., 521.],
        [  2.,   1.,   5.,  ...,   3.,   4.,   3.],
        [  1.,   1.,   2.,  ...,   1.,   1.,   3.],
        ...,
        [  0.,   0.,   0.,  ...,   1.,   0.,   1.],
        [  1.,   1.,   0.,  ...,   0.,   0.,   0.],
        [  1.,   1.,   1.,  ...,   1.,   1.,   1.]])
tensor([[8.5017e+07, 3.1491e+05, 2.7998e+05, 2.2730e+05, 2.1878e+08, 5.3672e+04,
         1.9385e+04, 2.5830e+04, 3.0905e+04, 2.5066e+04, 2.3370e+04, 2.9581e+04,
         1.1159e+05],
        [3.1491e+05, 1.4820e+03, 1.0850e+03, 8.6900e+02, 8.3022e+05, 1.9400e+02,
         8.3000e+01, 9.9000e+01, 1.0900e+02, 9.0000e+01, 9.7000e+01, 1.0200e+02,
         4.2400e+02],
        [2.7998e+05, 1.0850e+03, 1.1530e+03, 7.7300e+02, 7.5112e+05, 1.7800e+02,
         8.3000e+01, 8.9000e+01, 9.6000e+01, 8.2000e+01, 8.7000e+01, 1.1100e+02,
         3.8300e+02],
        [2.2730e+05, 8.6900e+02, 7.7300e+02, 7.3100e+02, 6.0586e+05, 1.5100e+02,
         5.7000e+01, 7.6000e+01, 7.9000e+01, 6.8000e+01, 6.0000e+01, 9.1000e+01,
         3.0900e+02],
        [2.1878e+08, 8.3022e+05, 7.5112e+05, 6.0586e+05, 5.8433e+08, 1.4468e+05,
         5.2589e+04, 7.0656e+04, 8.2216e+04, 6.6484e+04, 6.2755e+04, 8.2826e+04,
         2.9797e+05],
        [5.3672e+04, 1.9400e+02, 1.7800e+02, 1.5100e+02, 1.4468e+05, 7.4000e+01,
         1.7000e+01, 1.5000e+01, 2.1000e+01, 1.8000e+01, 1.9000e+01, 2.0000e+01,
         7.4000e+01],
        [1.9385e+04, 8.3000e+01, 8.3000e+01, 5.7000e+01, 5.2589e+04, 1.7000e+01,
         2.7000e+01, 0.0000e+00, 0.0000e+00, 6.0000e+00, 9.0000e+00, 5.0000e+00,
         2.7000e+01],
        [2.5830e+04, 9.9000e+01, 8.9000e+01, 7.6000e+01, 7.0656e+04, 1.5000e+01,
         0.0000e+00, 3.6000e+01, 0.0000e+00, 8.0000e+00, 6.0000e+00, 1.3000e+01,
         3.6000e+01],
        [3.0905e+04, 1.0900e+02, 9.6000e+01, 7.9000e+01, 8.2216e+04, 2.1000e+01,
         0.0000e+00, 0.0000e+00, 4.2000e+01, 1.6000e+01, 8.0000e+00, 8.0000e+00,
         4.2000e+01],
        [2.5066e+04, 9.0000e+01, 8.2000e+01, 6.8000e+01, 6.6484e+04, 1.8000e+01,
         6.0000e+00, 8.0000e+00, 1.6000e+01, 3.4000e+01, 0.0000e+00, 0.0000e+00,
         3.4000e+01],
        [2.3370e+04, 9.7000e+01, 8.7000e+01, 6.0000e+01, 6.2755e+04, 1.9000e+01,
         9.0000e+00, 6.0000e+00, 8.0000e+00, 0.0000e+00, 3.2000e+01, 0.0000e+00,
         3.2000e+01],
        [2.9581e+04, 1.0200e+02, 1.1100e+02, 9.1000e+01, 8.2826e+04, 2.0000e+01,
         5.0000e+00, 1.3000e+01, 8.0000e+00, 0.0000e+00, 0.0000e+00, 4.2000e+01,
         4.2000e+01],
        [1.1159e+05, 4.2400e+02, 3.8300e+02, 3.0900e+02, 2.9797e+05, 7.4000e+01,
         2.7000e+01, 3.6000e+01, 4.2000e+01, 3.4000e+01, 3.2000e+01, 4.2000e+01,
         1.5200e+02]])

In [31]:
x_inv=torch.inverse(x_mul)
print(x_inv)

tensor([[ 3.4058e-07, -3.6243e-06,  1.4917e-06, -1.7824e-06, -8.0525e-08,
          2.9677e-06,  1.1219e-05,  1.1210e-05,  5.7259e-06,  4.9404e-06,
          8.8998e-06,  1.8228e-05, -9.7894e-05],
        [-3.6242e-06,  3.6654e-03, -2.5667e-04, -3.2196e-04,  1.5984e-05,
          1.3109e-03, -5.8354e-04,  1.2140e-04,  7.5651e-04,  1.0403e-03,
         -2.9581e-04,  1.8080e-03, -3.9037e-02],
        [ 1.4917e-06, -2.5667e-04,  5.9282e-03,  4.7347e-04, -8.8699e-06,
          1.7445e-03, -4.0577e-03, -3.0964e-05,  7.5105e-04, -8.0220e-04,
         -1.9264e-03, -2.0380e-03,  1.9263e-03],
        [-1.7824e-06, -3.2196e-04,  4.7347e-04,  1.0091e-02, -6.1115e-06,
         -3.4114e-04, -1.2893e-03, -5.4906e-04,  1.5558e-03, -2.8334e-05,
          1.7077e-03, -1.4625e-03, -7.3726e-03],
        [-8.0511e-08,  1.5983e-05, -8.8692e-06, -6.1111e-06,  5.2425e-06,
          5.3300e-05,  9.6124e-05,  3.4639e-05,  4.8375e-05, -3.2982e-05,
         -6.8683e-05, -9.6951e-05, -1.0244e-02],
        [ 2.9679e-06,  1.3109e-03,  1.7445e-03, -3.4114e-04,  5.3300e-05,
          2.9020e-02, -4.5971e-03,  1.8003e-03,  2.2091e-04, -3.8524e-03,
         -6.4672e-03, -3.4925e-03, -1.2463e-01],
        [ 1.1219e-05, -5.8355e-04, -4.0577e-03, -1.2893e-03,  9.6123e-05,
         -4.5971e-03,  6.6382e-02,  2.2992e-02,  2.4021e-02, -7.0666e-03,
         -6.4885e-03,  1.3179e-03, -2.0125e-01],
        [ 1.1210e-05,  1.2139e-04, -3.0960e-05, -5.4905e-04,  3.4638e-05,
          1.8003e-03,  2.2992e-02,  5.0816e-02,  2.3427e-02, -7.7077e-03,
         -2.8611e-03, -3.5834e-03, -9.5429e-02],
        [ 5.7260e-06,  7.5651e-04,  7.5105e-04,  1.5558e-03,  4.8375e-05,
          2.2090e-04,  2.4021e-02,  2.3427e-02,  5.0101e-02, -1.3023e-02,
         -3.9443e-03, -2.2045e-04, -1.2616e-01],
        [ 4.9404e-06,  1.0403e-03, -8.0220e-04, -2.8330e-05, -3.2982e-05,
         -3.8524e-03, -7.0666e-03, -7.7077e-03, -1.3023e-02,  5.6939e-02,
          2.5339e-02,  2.4970e-02,  4.3791e-02],
        [ 8.8997e-06, -2.9580e-04, -1.9264e-03,  1.7077e-03, -6.8684e-05,
         -6.4672e-03, -6.4885e-03, -2.8612e-03, -3.9443e-03,  2.5339e-02,
          5.8049e-02,  2.5262e-02,  1.1152e-01],
        [ 1.8228e-05,  1.8080e-03, -2.0380e-03, -1.4625e-03, -9.6951e-05,
         -3.4925e-03,  1.3178e-03, -3.5834e-03, -2.2047e-04,  2.4970e-02,
          2.5262e-02,  5.2196e-02,  1.5679e-01],
        [-9.7917e-05, -3.9037e-02,  1.9268e-03, -7.3739e-03, -1.0244e-02,
         -1.2463e-01, -2.0125e-01, -9.5430e-02, -1.2616e-01,  4.3790e-02,
          1.1152e-01,  1.5679e-01,  2.0356e+01]])

In [32]:
fin=torch.matmul(x_inv,x_t)
print(fin)
fin=torch.matmul(fin,y_torch)
print(fin)

tensor([[-6.1263e-05,  5.5874e-05,  6.0880e-05,  ..., -3.8619e-05,
          5.0251e-05, -7.4516e-05],
        [ 2.8457e-04, -4.8994e-03,  8.6366e-03,  ...,  3.1615e-03,
          2.3686e-03,  2.5243e-03],
        [-7.9115e-03, -6.6934e-03, -1.3911e-03,  ..., -8.8546e-03,
         -7.7111e-03,  3.4234e-03],
        ...,
        [-1.0934e-03,  3.7897e-03, -7.9018e-04,  ...,  2.4871e-02,
         -1.5103e-02,  2.2622e-02],
        [ 2.9458e-02,  3.2173e-02, -2.4824e-04,  ..., -4.1388e-03,
         -1.8328e-02, -1.0458e-02],
        [ 5.7390e-01,  5.5188e-01, -4.8019e-01,  ..., -6.7052e-01,
          1.9032e-02, -5.2991e-01]])
tensor([[-8.9253e+01],
        [-3.4378e+04],
        [ 1.9266e+04],
        [-3.0555e+03],
        [-1.6269e+02],
        [-1.0685e+04],
        [ 3.1207e+04],
        [ 7.8266e+04],
        [ 3.2419e+04],
        [ 1.2718e+04],
        [ 5.6471e+04],
        [-3.0163e+04],
        [ 9.2065e+05]])

In [33]:
fin
print(x_tes.size())

torch.Size([38, 13])

In [34]:
y_pred=torch.matmul(x_tes,fin)

In [35]:
y_pred

tensor([[532639.8125],
        [548967.5625],
        [438796.0938],
        [578199.5000],
        [567625.3125],
        [473513.8438],
        [414069.8750],
        [516851.1562],
        [601449.5000],
        [455191.9375],
        [482421.6250],
        [484343.4062],
        [540833.7500],
        [390158.9375],
        [430246.6250],
        [589354.5000],
        [600701.7500],
        [445026.8750],
        [522192.9375],
        [370587.1250],
        [592419.3125],
        [388982.6250],
        [545110.2500],
        [593247.9375],
        [421178.5000],
        [362571.3750],
        [464040.2812],
        [646762.0625],
        [526564.3125],
        [404406.6875],
        [530795.6250],
        [598941.1875],
        [398611.9375],
        [519156.1250],
        [501154.1875],
        [544486.0000],
        [419458.9688],
        [455743.3750]])

In [36]:
val=(y_tes-y_pred)**2

In [37]:
val

tensor([[9.2287e+09, 1.2236e+11, 1.3182e+11,  ..., 1.7082e+10, 2.3024e+10,
         8.1386e+09],
        [6.3582e+09, 1.1120e+11, 1.4394e+11,  ..., 1.3080e+10, 1.8336e+10,
         5.4592e+09],
        [3.6066e+10, 1.9682e+11, 7.2481e+10,  ..., 5.0419e+10, 6.0310e+10,
         3.3877e+10],
        ...,
        [7.0930e+09, 1.1421e+11, 1.4056e+11,  ..., 1.4126e+10, 1.9570e+10,
         6.1415e+09],
        [4.3784e+10, 2.1435e+11, 6.2442e+10,  ..., 5.9476e+10, 7.0182e+10,
         4.1370e+10],
        [2.9916e+10, 1.8207e+11, 8.1893e+10,  ..., 4.3095e+10, 5.2274e+10,
         2.7926e+10]])

In [38]:
mse=1/len(val)*(sum(val))
mse
me=sum(mse)/len(mse)
print(me)

tensor(5.8915e+10)

In [39]:
w = torch.linalg.pinv(x_torch)
w=torch.matmul(w,y_torch)
w

tensor([[   -84.5214],
        [-32746.5352],
        [ 19326.2891],
        [ -2762.2236],
        [   300.1104],
        [ -5045.9365],
        [ 40339.4609],
        [ 82607.4141],
        [ 38149.4062],
        [ 10710.9883],
        [ 51402.2031],
        [-37270.5469],
        [   913.2918]])

In [40]:
y_pred=torch.matmul(x_tes,w)
val=(y_tes-y_pred)**2
mse=1/len(val)*(sum(val))
mse
me=sum(mse)/len(mse)
print(me)

tensor(5.8274e+10)

In [41]:
x_torch

tensor([[502.,   2.,   1.,  ...,   0.,   1.,   1.],
        [841.,   1.,   1.,  ...,   0.,   1.,   1.],
        [940.,   5.,   2.,  ...,   0.,   0.,   1.],
        ...,
        [633.,   3.,   1.,  ...,   1.,   0.,   1.],
        [917.,   4.,   1.,  ...,   0.,   0.,   1.],
        [521.,   3.,   3.,  ...,   1.,   0.,   1.]])

In [42]:
w= torch.linalg.lstsq(x_torch, y_torch, driver='gelsd').solution

In [43]:
y_pred=torch.matmul(x_tes,w)
val=(y_tes-y_pred)**2
mse=1/len(val)*(sum(val))
mse
me=sum(mse)/len(mse)
print(me)

tensor(5.8275e+10)

In [44]:
weights = torch.linalg.lstsq(x_torch, y_torch, driver='gelsd').solution

y_pred = x_tes @ weights

mse = torch.mean((y_tes - y_pred)**2)
rmse = torch.sqrt(mse)
rmse

tensor(241401.5000)

In [45]:
import torch.nn as nn
input_dim = x_torch.shape[1]
model = nn.Linear(input_dim, 1, bias=False)
optimizer = torch.optim.Adam(model.parameters(), lr=10)
criterion = nn.MSELoss()
epochs = 30000
for epoch in range(epochs):
    # Forward pass
    y_pred = model(x_torch)
    loss = criterion(y_pred, y_torch)
    
    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 500 == 0:
        current_rmse = torch.sqrt(loss).item()
        print(f'Epoch [{epoch+1}/{epochs}], RMSE: ${current_rmse:,.2f}')

model.eval()
with torch.no_grad():
    test_pred = model(x_tes)
    test_rmse = torch.sqrt(torch.mean((y_tes.reshape(-1,1) - test_pred)**2))
    print(f'\n--- Final Test RMSE: ${test_rmse.item():,.2f} ---')

Epoch [500/30000], RMSE: $275,894.53
Epoch [1000/30000], RMSE: $274,747.56
Epoch [1500/30000], RMSE: $273,851.00
Epoch [2000/30000], RMSE: $272,940.16
Epoch [2500/30000], RMSE: $272,080.06
Epoch [3000/30000], RMSE: $271,312.88
Epoch [3500/30000], RMSE: $270,661.66
Epoch [4000/30000], RMSE: $270,133.84
Epoch [4500/30000], RMSE: $269,724.84
Epoch [5000/30000], RMSE: $269,421.28
Epoch [5500/30000], RMSE: $269,204.06
Epoch [6000/30000], RMSE: $269,052.41
Epoch [6500/30000], RMSE: $268,946.56
Epoch [7000/30000], RMSE: $268,870.59
Epoch [7500/30000], RMSE: $268,813.47
Epoch [8000/30000], RMSE: $268,768.81
Epoch [8500/30000], RMSE: $268,733.59
Epoch [9000/30000], RMSE: $268,706.56
Epoch [9500/30000], RMSE: $268,686.44
Epoch [10000/30000], RMSE: $268,672.06
Epoch [10500/30000], RMSE: $268,662.28
Epoch [11000/30000], RMSE: $268,655.91
Epoch [11500/30000], RMSE: $268,651.81
Epoch [12000/30000], RMSE: $268,648.97
Epoch [12500/30000], RMSE: $268,646.75
Epoch [13000/30000], RMSE: $268,644.72
Epoch [13500/30000], RMSE: $268,642.75
Epoch [14000/30000], RMSE: $268,644.59
Epoch [14500/30000], RMSE: $268,638.88
Epoch [15000/30000], RMSE: $268,636.94
Epoch [15500/30000], RMSE: $268,635.00
Epoch [16000/30000], RMSE: $268,633.06
Epoch [16500/30000], RMSE: $268,631.19
Epoch [17000/30000], RMSE: $268,629.25
Epoch [17500/30000], RMSE: $268,627.34
Epoch [18000/30000], RMSE: $268,625.47
Epoch [18500/30000], RMSE: $268,623.59
Epoch [19000/30000], RMSE: $268,622.06
Epoch [19500/30000], RMSE: $268,619.84
Epoch [20000/30000], RMSE: $268,618.00
Epoch [20500/30000], RMSE: $268,616.16
Epoch [21000/30000], RMSE: $268,614.41
Epoch [21500/30000], RMSE: $268,612.50
Epoch [22000/30000], RMSE: $268,610.66
Epoch [22500/30000], RMSE: $268,613.09
Epoch [23000/30000], RMSE: $268,607.47
Epoch [23500/30000], RMSE: $268,605.19
Epoch [24000/30000], RMSE: $268,603.38
Epoch [24500/30000], RMSE: $268,601.56
Epoch [25000/30000], RMSE: $268,599.78
Epoch [25500/30000], RMSE: $268,598.00
Epoch [26000/30000], RMSE: $268,596.22
Epoch [26500/30000], RMSE: $268,594.78
Epoch [27000/30000], RMSE: $268,592.69
Epoch [27500/30000], RMSE: $268,597.62
Epoch [28000/30000], RMSE: $268,589.16
Epoch [28500/30000], RMSE: $268,587.59
Epoch [29000/30000], RMSE: $268,585.72
Epoch [29500/30000], RMSE: $268,583.94
Epoch [30000/30000], RMSE: $268,582.25

--- Final Test RMSE: $236,974.69 ---